min_particles: 500
max_particles: 2000

kld_err: 0.05
kld_z: 0.99

update_min_d: 0.2
update_min_a: 0.2

resample_interval: 1

transform_tolerance: 0.5
recovery_alpha_slow: 0.0
recovery_alpha_fast: 0.0

# Laser model
laser_min_range: 0.1
laser_max_range: 10.0
laser_z_hit: 0.95
laser_z_rand: 0.05
laser_sigma_hit: 0.2
laser_lambda_short: 0.1

laser_model_type: likelihood_field

# Odometry model (tune if drift is bad)
odom_alpha1: 0.2
odom_alpha2: 0.2
odom_alpha3: 0.2
odom_alpha4: 0.2
odom_alpha5: 0.1
