DWAPlannerROS:
  # ========= GOAL TOLERANCE ("radius") =========
  xy_goal_tolerance: 0.50        # 0.5 m radius around goal
  yaw_goal_tolerance: 0.50       # ~28.6 degrees
  latch_xy_goal_tolerance: true  # once inside radius, don't back out
